### PR TITLE
Docs 2.0 - Part 2

### PR DESCRIPTION
**Pull request by bennylp**
This PR contains **Part 2** of doc 2.0 task list [1].
Preview the latest doc 2.0 in https://docs.pjsip.org/en/docs_2_0/
Note that it may take up to 15 minutes to build from the source after an update

Any inputs big and small are welcome. Stuffs that could get some reviews for example:
- the general structure of the site in general
- are there any features that are note listed
- filling in missing parts/instructions would be great
- spell checking/grammars to read better

----
[1] Doc 2.0 task list:

- [x] Part 1: Docker image for building documentation (done, already in master, pls see Readme)
- [x] Part 2: introducing the main layout (main menu), and  the following sections
        - Overview
        - Get started (minus guide for each platform, see part 3)
        - PJSUA2 Guide
        - API reference & samples
- [ ] Part 3: PJSUA Guide
- [ ] Part 4: **Get started** sections:
       - Android
       - iPhone
       - Posix
       - Windows
       - Windows Phone
- [ ] Part 5: Specific guide section (porting from existing guide and FAQ. There will be no more FAQ)

### CODE REVIEW

**Comment by nanangizz** [comment]
FYI, there is also 'PJSUA guide' in the 2.13 task, perhaps insert it into the list/index?

**Comment by bennylp** [comment]
> FYI, there is also 'PJSUA guide' in the 2.13 task, perhaps insert it into the list/index?

Ok. Since I see that you're the one that has been assigned to do it, where do you want to put it in the list? :D

**Comment by nanangizz** [comment]
> Ok. Since I see that you're the one that has been assigned to do it, where do you want to put it in the list? :D

Yes, it's my task :D
So, in part 2 before 'PJSUA2 Guide' perhaps.

**Comment by bennylp** [comment]
> Yes, it's my task :D
> So, in part 2 before 'PJSUA2 Guide' perhaps.

I put it as part 3 and renumbered the list. I didn't put in part 2 because each part ideally is equal to one PR. Parts don't have to complete serially

**Review by sauwming — APPROVED** [review]

**Review by nanangizz — APPROVED** [review]

**Review by ismangil — APPROVED** [review]

**Review by trengginas — APPROVED** [review]

**Pull request merged**
